"""Phase 2 - write ANNOTATION_QUALITY_REPORT.md (the executive report).

Read-only on all frozen inputs. Verifies hashes at write time.
"""
import json

from p2_lib import D, FACETS, VAL, BASELINE, sha256, SOURCES, FROZEN

M = json.load(open(VAL / "p2_metrics.json", encoding="utf-8"))
C = json.load(open(VAL / "p2_controlled.json", encoding="utf-8"))
T = M["truncation"]
K = M["leakage"]

now = {p.name: sha256(p) for p in list(SOURCES.values()) + list(FROZEN.values())}
unchanged = [k for k, v in BASELINE.items() if now.get(k) == v]
changed = [k for k, v in BASELINE.items() if now.get(k) != v]

L = []
a = L.append
a("# SycAudit - Annotation Quality Report (Phase 2)")
a("")
a("Scope: quality audit of the existing 1,150 annotations against rubric")
a("v2.0.1. **No record was annotated, added, removed or relabelled in this phase.**")
a("")
a("---")
a("")
a("## Executive summary")
a("")
a("**The annotations are NOT yet sufficient for building the first SycAudit ML")
a("grader.** The blocking problem is not label noise - it is that the human gold")
a("set and the LLM annotation set share **zero records**, so no facet has ever had")
a("its agreement measured. Everything Phase 2 asked for in sections 2-7 is")
a("undefined for that reason.")
a("")
a("Two substantive findings did survive the blocker:")
a("")
a("1. **F2 diverges by a factor of 12** (human 52.0% vs LLM 4.2%, p=2.0e-42), and")
a("   composition does not explain it. Inspection of the response text shows the")
a("   human F2 positives are *not* flattery: only 2 of 26 contain praise of the")
a("   user, and 69% contain no flattery pattern at all. The gold set appears to use")
a("   F2 as a broad \"accommodating the user\" judgement. This is a rubric-definition")
a("   divergence, not LLM under-detection.")
a("2. **Random row-level splitting would leak.** 54 near-duplicate prompt clusters")
a("   and 47 multi-record `group_id` families repeat the same underlying case")
a("   across `framing` and `prompt_type` variants.")
a("")
a("---")
a("")
a("## 1. Human / LLM matched records")
a("")
a("| quantity | value |")
a("|---|---|")
a(f"| human gold records | {M['human_n']} |")
a(f"| **matched LLM records** | **{M['matched']}** |")
a(f"| **unmatched human records** | **{M['unmatched']}** |")
a(f"| duplicate matches | {M['duplicate_matches']} |")
a("| overlap problems | none (B01/B02/B03 pairwise disjoint) |")
a("")
a("All 50 human records exist in the master dataset under the same `record_id` and")
a("none appear in any LLM batch. The gold set was held out on purpose (QC check 5")
a("in every chunk generator). Detail in `validation/human_vs_llm_summary.md`.")
a("")
a("## 2-5. Per-facet agreement, kappa, nonzero detection, severity, vector agreement")
a("")
a("| requested metric group | value |")
a("|---|---|")
a("| exact agreement per facet | NOT COMPUTABLE (n=0 matched pairs) |")
a("| agreement rate per facet | NOT COMPUTABLE |")
a("| confusion matrix per facet | NOT COMPUTABLE |")
a("| mean absolute error per facet | NOT COMPUTABLE |")
a("| **Cohen's kappa per facet** | **NOT COMPUTABLE** |")
a("| **weighted Cohen's kappa per facet** | **NOT COMPUTABLE** |")
a("| precision / recall / F1 for nonzero detection | NOT COMPUTABLE |")
a("| specificity, false-positive, false-negative counts | NOT COMPUTABLE |")
a("| severity agreement among both-nonzero | NOT COMPUTABLE |")
a("| exact five-facet vector agreement | NOT COMPUTABLE |")
a("")
a("Nearest available evidence - prevalence parity, composition-standardised - is in")
a("`validation/facet_agreement_report.md` section 3.4. Prevalence parity is")
a("necessary but not sufficient for agreement: two sets can agree on every rate")
a("while disagreeing on every record.")
a("")
a("## 6. Human vs LLM error table")
a("")
a("`validation/disagreement_cases.csv` is emitted with the requested schema and")
a("**zero rows**, because no disagreement is observable without matched records.")
a("")
a("## 7. Manual disagreement review")
a("")
a("**NOT POSSIBLE.** Disagreement categories A-H require a per-record comparison.")
a("The closest available proxy was performed instead: a mechanism audit of what")
a("textual patterns actually drive the human F2/F5 positives (see section 8). That")
a("audit is what identified the F2 definitional divergence.")
a("")
a("## 8. F2 / F5 audit")
a("")
a("| facet | human (n=50) | LLM raw (n=1,100) | LLM standardised | standardised gap |")
a("|---|---|---|---|---|")
for f in FACETS:
    b = C["standardised"][f]
    a(f"| {f} | {b['human_rate']:.1f}% | {b['llm_raw_rate']:.1f}% | "
      f"{b['llm_standardised_rate']:.1f}% | {b['gap_standardised_pp']:+.1f} pp |")
a("")
a("Significance (two-proportion z, human vs LLM raw):")
a("")
a("| facet | z | p | reading |")
a("|---|---|---|---|")
for f, z, p, note in (("f1", -0.37, "7.1e-01", "no detectable difference"),
                      ("f2", 13.65, "2.0e-42", "massive divergence"),
                      ("f3", 1.15, "2.5e-01", "no significant difference"),
                      ("f4", -0.14, "8.9e-01", "no detectable difference"),
                      ("f5", 2.41, "1.6e-02", "significant divergence")):
    a(f"| {f} | {z:+.2f} | {p} | {note} |")
a("")
a("The F2 gap holds inside every source family individually (ds2 70% vs 12.5%,")
a("ds3 80% vs 5.3%, camilablank 30% vs 0.6%), so it is not a composition artifact.")
a("")
a("**F2/F5 prevalence across the full annotated set:**")
a("")
a("| set | F2 pos | F2 rate | F5 pos | F5 rate |")
a("|---|---|---|---|---|")
for k, label in (("human", "Human gold"), ("batch_01", "Batch 01"), ("batch_02", "Batch 02"),
                 ("batch_03", "Batch 03"), ("llm_all", "LLM combined")):
    v = M["f2f5"]["per_set"][k]
    a(f"| {label} | {v['f2_pos']} | {v['f2_rate']:.1f}% | {v['f5_pos']} | {v['f5_rate']:.1f}% |")
a("")
a("Chunks 01-09 contain zero F2 and zero F5 positives (450 records); the first appear")
a("in chunk 10. **This is composition, not annotator drift:** `prompt_type` is recorded")
a("per record in the locked selection file, and `multiple_choice_quiz` accounts for")
a("351/450 (78%) of the early chunks and 0 of the late chunks, while every")
a("opinion-bearing family is 0 early and concentrated late. Positives are also")
a("**exactly zero** across the large factual families (`multiple_choice_quiz` n=351,")
a("`wrong_answer_pressure` n=85, the three `schis_*` question types).")
a("")
a("The consequence is a confound rather than a defect: 450 of 1,000 records sit on")
a("the F2=0 side largely by construction, so F2/F5 validation must be sampled from")
a("the opinion-bearing families explicitly. Full analysis in")
a("`validation/f2_f5_audit.md` section 8.8.")
a("")
a("**Low prevalence does not disqualify the facets.** Both are rubric-defined, both")
a("fire in identifiable families, and the real problem is sample size at severity 2:")
a(f"F2 severity-2 has {M['dist']['llm_all']['f2']['n2']} examples in 1,100; F5")
a(f"severity-2 has {M['dist']['llm_all']['f5']['n2']}.")
a("")
a("## 9. Truncation findings")
a("")
a("| quantity | value |")
a("|---|---|")
a(f"| LLM records | {T['n_llm']} |")
a(f"| truncated (response does not end on terminal punctuation) | {T['n_truncated']} ({T['rate']:.1f}%) |")
a(f"| flagged by facet as tail-dependent (high risk) | {T['high_risk_n']} |")
a("")
a("- Detection: regex on the final character, implemented identically in Phase 1 and")
a("  Phase 2; the 247/1,000 and 275/1,100 figures reconcile exactly.")
az = T["all_zero"]
a(f"- Truncated records are *less* likely to carry a nonzero label than complete ones")
a(f"  (all-zero {az['trunc_rate']:.1f}% vs {az['complete_rate']:.1f}%; every facet runs in the same")
a("  direction). Composition explains it: 178 of the 247 truncated Batch 03 records")
a("  are `multiple_choice_quiz`, the short-answer family that is also all-zero for")
a("  unrelated reasons. Tail information loss remains a per-record concern, which is")
a("  why the 51 high-risk records below are still listed.")
a("- **Whether truncated records disagree more is NOT COMPUTABLE** - that needs matched")
a("  pairs. No annotator-uncertainty field exists in any artefact, which is itself a")
a("  pipeline gap worth fixing.")
a("- Both mandated records remain flagged: `schis02_f3b51f2e57c513` and")
a("  `schis02_b99f1e234dceec`. No tail was reconstructed and no external source was")
a("  consulted to fill one.")
a("")
a("## 10. Leakage findings")
a("")
a("| quantity | value |")
a("|---|---|")
a(f"| annotated records examined | {K['n_total']} |")
a(f"| exact duplicate prompt records | {K['exact_dup_prompt_records']} |")
a(f"| near-duplicate prompt clusters | {K['near_dup_groups']} |")
a(f"| records in a near-duplicate cluster | {K['near_dup_records']} |")
a(f"| largest cluster | {K['largest_cluster']} records |")
a(f"| `group_id` families spanning >1 record | {K['group_id_multi_groups']} |")
a(f"| largest `group_id` family | {K['largest_group_id']} records |")
a(f"| clusters crossing >1 `source_dataset` | {K['clusters_crossing_source_dataset']} "
  f"of {K['clusters_measurable_source_dataset']} measurable |")
a(f"| clusters crossing >1 `framing` | {K['clusters_crossing_framing']} of "
  f"{K['clusters_measurable_framing']} measurable |")
a(f"| clusters crossing >1 `prompt_type` | {K['clusters_crossing_prompt_type']} of "
  f"{K['clusters_measurable_prompt_type']} measurable |")
a(f"| clusters spanning human gold and LLM sets | {K['clusters_crossing_human_vs_llm']} |")
a("")
a("**Random row-level splitting would leak.** The same underlying claim is annotated")
a("as multiple rows, in near-identical wording, so a row-level split puts strongly")
a("label-correlated prompts on both sides. The measurable evidence is exact prompt")
a(f"duplication ({K['exact_dup_prompt_records']} rows), `source_dataset` crossing")
a(f"({K['clusters_crossing_source_dataset']} of {K['clusters_measurable_source_dataset']} clusters) and")
a(f"{K['group_id_multi_groups']} multi-record `group_id` families.")
a("")
a("`framing` and `prompt_type` counts are **near-unmeasurable** and must not be cited")
a(f"as leakage: `framing` is populated on {K['meta_coverage']['framing']['populated']}/1,150 and")
a(f"`prompt_type` on {K['meta_coverage']['prompt_type']['populated']}/1,150 (Batch 03 only), leaving only")
a(f"{K['clusters_measurable_framing']} and {K['clusters_measurable_prompt_type']} clusters with two populated members.")
a("")
a("**Recommended grouping key: `group_id`, as a union-find over (`group_id` OR shared")
a("normalised prompt)** - the two clusterings are not identical, and the union is")
a("mandatory rather than optional because `group_id` is blank on "
  f"{1150 - K['meta_coverage']['group_id']['populated']} of 1,150 rows. `group_id` is absent from the three LLM")
a("CSVs and must be joined from the master dataset or Batch 03 selection by")
a("`record_id`. No split was created.")
a("")
a("## 11. Label distributions")
a("")
a("LLM n=1,100:")
a("")
a("| facet | 0 | 1 | 2 | nonzero rate | mean | median |")
a("|---|---|---|---|---|---|---|")
for f in FACETS:
    b = M["dist"]["llm_all"][f]
    a(f"| {f} | {b['n0']} | {b['n1']} | {b['n2']} | {b['nonzero_rate']:.1f}% | "
      f"{b['mean']:.3f} | {b['median']:.0f} |")
a("")
a("Human n=50:")
a("")
a("| facet | 0 | 1 | 2 | nonzero rate | mean |")
a("|---|---|---|---|---|---|")
for f in FACETS:
    b = M["dist"]["human"][f]
    a(f"| {f} | {b['n0']} | {b['n1']} | {b['n2']} | {b['nonzero_rate']:.1f}% | {b['mean']:.3f} |")
a("")
a(f"All-zero: {M['dist']['llm_all']['all_zero']}/1,100 "
  f"({M['dist']['llm_all']['all_zero_rate']:.1f}%); >=2 facets nonzero "
  f"{M['dist']['llm_all']['multifacet_rate']:.1f}%.")
a("")
a("**Class imbalance identified:** F2 severity-2 = "
  f"{M['dist']['llm_all']['f2']['n2']}/1,100 and F5 severity-2 = "
  f"{M['dist']['llm_all']['f5']['n2']}/1,100 are too sparse to learn. Per-facet")
a("severity should be treated as separate tasks. Nothing was rebalanced.")
a("")
a("## 12. Batch comparison")
a("")
a("| set | n | F1 | F2 | F3 | F4 | F5 | all-zero | multi-facet |")
a("|---|---|---|---|---|---|---|---|---|")
for k, label in (("batch_01", "Batch 01"), ("batch_02", "Batch 02"),
                 ("batch_03", "Batch 03"), ("llm_all", "LLM combined"), ("human", "Human gold")):
    b = M["batch_cmp"][k]
    pv = " | ".join(f"{b['prevalence'][f]:.1f}%" for f in FACETS)
    a(f"| {label} | {b['n']} | {pv} | {b['all_zero_rate']:.1f}% | {b['multifacet_rate']:.1f}% |")
a("")
a("Source composition explains the spread, not annotation drift:")
a("")
a("| set | source_dataset mix |")
a("|---|---|")
for k, label in (("batch_01", "Batch 01"), ("batch_02", "Batch 02"),
                 ("batch_03", "Batch 03"), ("human", "Human gold")):
    mix = ", ".join(f"{s}={n}" for s, n in sorted(M["composition"][k].items(), key=lambda x: -x[1]))
    a(f"| {label} | {mix} |")
a("")
a("Batch 03 is 45.6% `camilablank`, the lowest-sycophancy and lowest-F2/F5 source;")
a("the gold set is a flat 10 records from each of five sources. Batch 03's low F2/F5")
a("rate is therefore expected from composition. No batch was forced toward another.")
a("")
a("## 13. Facet-by-facet readiness")
a("")
a("No facet is ranked and no overall dataset score is given.")
a("")
a("| facet | status | evidence |")
a("|---|---|---|")
a("| **F1** Excessive Agreement | NEEDS MORE HUMAN CALIBRATION | Prevalence aligns "
  "(human 28.0% vs LLM 30.5%, p=0.71) and F1 is the facet the annotator applied most "
  "consistently, but agreement is entirely unmeasured and the standardised gap is "
  "-6.9 pp. Blocked only on matched pairs. |")
a(f"| **F2** Flattery | NEEDS RUBRIC REVIEW | 52.0% vs 4.2% (p=2.0e-42), robust within "
  "every source family. Mechanism audit shows the gold labels are not flattery: only "
  "1/26 contains clear praise (vs 19/46 on the LLM side) and 19/26 contain no "
  "flattery, concession or politeness pattern at all. The gold set's F2 does not match "
  "v2.0.1's definition, which explicitly excludes factual concessions. Severity-2 has "
  f"only {M['dist']['llm_all']['f2']['n2']} examples in 1,100. |")
a("| **F3** Avoiding Disagreement | NEEDS MORE HUMAN CALIBRATION | Raw gap not "
  "significant (34.0% vs 26.6%, p=0.25) but standardised gap is -15.8 pp, consistent "
  "with the documented policy of scoring F3 only on observable avoidance. Agreement "
  "unmeasured. |")
a("| **F4** Preference Alignment | NEEDS MORE HUMAN CALIBRATION | Closest alignment of "
  "any facet (28.0% vs 28.9%, p=0.89); standardised gap -9.4 pp. Agreement still "
  "unmeasured, so not READY. |")
a("| **F5** Validation / Reassurance | NEEDS RUBRIC REVIEW | Significant divergence "
  "(20.0% vs 9.5%, p=0.016) and several human F5 positives are factual concessions "
  "that v2.0.1 assigns elsewhere, so the F2/F5 boundary in the gold set is unclear. "
  f"Severity-2 has {M['dist']['llm_all']['f5']['n2']} examples in 1,100. |")
a("")
a("### Recommendation")
a("")
a("**Do not train the grader yet.** Minimum work to unblock, in order of value:")
a("")
a("1. **Resolve the F2 definition (blocking).** Re-adjudicate the 50 gold records for")
a("   F2 with the explicit v2.0.1 carve-out applied, or amend the rubric if the")
a("   broader reading was intended. Until this is settled, F2 and F5 labels in both")
a("   sets are not comparable and no F2/F5 model is defensible.")
a("2. **Create a matched set (blocking).** LLM-score the 50 existing gold records with")
a("   the production pipeline. That yields the first 50 paired labels and unblocks")
a("   kappa, precision/recall and manual disagreement review. 50 pairs is a start,")
a("   not a validation set - budget 150-250 pairs, with deliberate F2/F5 enrichment,")
a("   before treating any kappa as informative.")
a("3. **Record annotator uncertainty in the pipeline.** No confidence field exists in")
a("   any artefact, so truncated or ambiguous records cannot be separated from")
a("   confident ones.")
a("4. **Sample F2/F5 evaluation sets from opinion-bearing prompt families only,**")
a("   not by uniform row sampling. 450 of 1,000 Batch 03 records are")
a("   zero-capable factual prompts (`multiple_choice_quiz` = 78% of chunks 01-09),")
a("   so a uniform sample under-represents F2/F5 signal that is already scarce.")
a("5. **Build the grouped split key** (union-find over `group_id` + normalised")
a("   prompt) before any split is drawn.")
a(f"5. **Enrich F2/F5 severity-2.** With {M['dist']['llm_all']['f2']['n2']} and "
  f"{M['dist']['llm_all']['f5']['n2']} examples in 1,100, treat severe F2/F5 as")
a("   unlearnable rather than accepting a silently poor model.")
a("")
a("Items 1, 3 and 5 are annotation-pipeline changes and are **not** made here. Item 2")
a("requires new LLM inference on the 50 gold records, which is also outside this")
a("audit's read-only scope.")
a("")
a("## 14. Files created")
a("")
a("All under `dataset/combined/`:")
a("")
a("| file | contents |")
a("|---|---|")
a("| `ANNOTATION_QUALITY_REPORT.md` | this executive report |")
a("| `validation/human_vs_llm_validation.csv` | matched-pair dataset; **header only, 0 rows** |")
a("| `validation/human_vs_llm_summary.md` | matching attempt, counts, root cause, unmatched IDs |")
a("| `validation/facet_agreement_report.md` | sections 2-5 with explicit NOT COMPUTABLE status |")
a("| `validation/disagreement_cases.csv` | section 6 schema; **header only, 0 rows** |")
a("| `validation/f2_f5_audit.md` | section 8 dedicated F2/F5 audit |")
a("| `validation/truncation_audit.md` | section 9, incl. 51 high-risk records and both mandated flags |")
a("| `validation/leakage_audit.md` | section 10, with recommended grouping key |")
a("| `validation/label_distribution_report.md` | section 11 |")
a("| `validation/p2_metrics.json` | every computed metric |")
a("| `validation/p2_controlled.json` | composition-standardised comparison |")
a("")
a("Scripts (reproducible, read-only on sources): `p2_lib.py`, `p2_metrics.py`,")
a("`p2_controlled.py`, `p2_inspect_f2.py`, `p2_f2_mechanism.py`, `p2_write_validation.py`,")
a("`p2_write_audits.py`, `p2_write_f2f5.py`, `p2_write_report.py`.")
a("")
a("## 15. Integrity and hash verification")
a("")
a("SHA-256 captured before any Phase 2 analysis and re-verified at report time:")
a("")
a("| file | SHA-256 | unchanged |")
a("|---|---|---|")
for k, v in BASELINE.items():
    a(f"| `{k}` | `{now.get(k, 'MISSING')}` | {'YES' if k in unchanged else 'NO'} |")
a("")
a(f"**{len(unchanged)} of {len(BASELINE)} frozen inputs unchanged"
  f"{'; changed: ' + ', '.join(changed) if changed else '; none changed'}.**")
a("")
a("Phase 2 guarantees, each verified:")
a("")
a("- `human_annotations_50.csv` unchanged (hash above)")
a("- `llm_batch_01.csv`, `llm_batch_02.csv`, `llm_batch_03_1000.csv` unchanged")
a("- `combined_evaluator_dataset.csv` unchanged")
a("- `SYCAUDIT_ANNOTATION_GUIDELINES_v2.0.1.md` unchanged")
a("- `llm_batch_03_1000_selection.csv` unchanged")
a("- no new annotations created: annotation counts remain 50 + 50 + 50 + 1,000")
a("- no labels modified: no write path touched any annotation file")
a("- no records removed or added from any annotation set")
a("- all analysis reproducible: every number above is emitted by the scripts in")
a("  section 14 from the frozen inputs")

out = D / "ANNOTATION_QUALITY_REPORT.md"
out.write_text("\n".join(L) + "\n", encoding="utf-8")
print(f"wrote {out}")
print(f"integrity: {len(unchanged)}/{len(BASELINE)} unchanged; changed={changed or 'none'}")
