import json
import os
import re
import collections

BASE = r"C:\Users\Ishika\Desktop\sycAudit\dataset"
SEL = os.path.join(BASE, "selected")

DS_FILES = {
    "ds1": os.path.join(SEL, "ds1_700.jsonl"),
    "ds2": os.path.join(SEL, "ds2_700.jsonl"),
    "ds3": os.path.join(SEL, "ds3_700.jsonl"),
}
UNIFIED = os.path.join(SEL, "unified_2100.jsonl")

def load(path):
    rows = []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows

DS = {k: load(v) for k, v in DS_FILES.items()}
UNI = load(UNIFIED)

lines = []
L = lines.append

TRIM = lambda s: (s[:180] + "..." if len(s) > 180 else s)

def norm(txt):
    txt = txt or ""
    return re.sub(r"\s+", " ", txt).strip().lower()

def norm_ws(s):
    return re.sub(r"\s+", " ", s or "").strip()

# ---------------------------------------------------------------------------
# 1. BASIC VALIDATION
# ---------------------------------------------------------------------------
L("# Quality Audit — Selected 2100 Records")
L("")
L("Generated by a deterministic script-based audit over the selected JSONL files. "
  "No records were modified.")
L("")

L("## 1. Basic Validation")
L("")
L("| Dataset | Expected | Actual | OK |")
L("|---|---|---|---|")
for ds in ("ds1", "ds2", "ds3"):
    exp = 700
    act = len(DS[ds])
    L("| %s | %d | %d | %s |" % (ds, exp, act, "OK" if act == exp else "FAIL"))
L("| unified | 2100 | %d | %s |" % (len(UNI), "OK" if len(UNI) == 2100 else "FAIL"))
L("")

REQUIRED = ["id", "source_dataset", "source_id", "prompt", "response",
            "f1", "f2", "f3", "f4", "f5"]
FIELDS = ["f1", "f2", "f3", "f4", "f5"]

L("### Required fields present")
L("")
L("| Dataset | Records | Records missing required field | Missing field(s) |")
L("|---|---|---|---|")
for ds in ("ds1", "ds2", "ds3", "unified"):
    rows = DS[ds] if ds != "unified" else UNI
    miss = collections.Counter()
    n_missing = 0
    for r in rows:
        for f in REQUIRED:
            if f not in r:
                miss[f] += 1
                n_missing += 1
    L("| %s | %d | %d | %s |" % (ds, len(rows), n_missing,
                                 (dict(miss) if miss else "none")))
L("")

L("### f1-f5 must be NULL")
L("")
L("| Dataset | Records | f1-f5 non-null count | Details |")
L("|---|---|---|---|")
for ds in ("ds1", "ds2", "ds3", "unified"):
    rows = DS[ds] if ds != "unified" else UNI
    bad = []
    for r in rows:
        nonnull = [f for f in FIELDS if r.get(f) is not None]
        if nonnull:
            bad.append((r.get("id"), nonnull))
    L("| %s | %d | %d | %s |" % (ds, len(rows), len(bad),
        ("first: %r" % (bad[:3],) if bad else "all NULL")))
L("")

L("### id uniqueness")
L("")
ids_all = [r["id"] for r in UNI]
dup_ids = [i for i, c in collections.Counter(ids_all).items() if c > 1]
L("unified ids: %d total, %d unique, %d duplicated ids" %
  (len(ids_all), len(set(ids_all)), len(dup_ids)))
L("")

# ---------------------------------------------------------------------------
# 2. SOURCE DISTRIBUTION
# ---------------------------------------------------------------------------
L("## 2. Source Distribution")
L("")

def fmt_counter(c, limit=30):
    return ", ".join("%s=%d" % (k, v) for k, v in c.most_common(limit))

def none_str(v):
    return "(none)" if v is None else v

# ---- DS1 ----
L("### DS1 — sycophancy-false-premises")
L("")
ds1 = DS["ds1"]
files = collections.Counter(r["source_file"] for r in ds1)
L("**records:** %d" % len(ds1))
L("")
L("**files represented (%d):**" % len(files))
for f, c in sorted(files.items()):
    L("- %d × `%s`" % (c, f))
L("")
models = collections.Counter(none_str(r.get("model") or r.get("model_id")) for r in ds1)
L("**models (%d):** %s" % (len(models), fmt_counter(models)))
L("")
framings = collections.Counter(none_str(r.get("framing")) for r in ds1)
frames_non_none = {k: v for k, v in framings.items() if k != "(none)"}
L("**framings (%d):**" % len(frames_non_none))
for k, v in framings.most_common():
    L("- %s = %d" % (k, v))
L("")
cats = collections.Counter(none_str(r.get("category")) for r in ds1)
L("**categories (%d):** %s" % (len(cats), fmt_counter(cats)))
L("")
L("**labels available:**")
L("- gpt4o_label present: %d" % sum(1 for r in ds1 if r.get("gpt4o_label")))
L("- human_label present: %d" % sum(1 for r in ds1 if r.get("human_label")))
L("- ablation_label present: %d" % sum(1 for r in ds1 if r.get("ablation_label")))
L("- ground_truth present: %d" % sum(1 for r in ds1 if r.get("ground_truth")))
L("")
L("**unique source IDs:** %d" % len(set(r["source_id"] for r in ds1)))
L("**unique prompts:** %d" % len(set(r["prompt"] for r in ds1)))
prompt_ids = set()
for r in ds1:
    sf = r.get("source_file") or ""
    if "ablation" in sf:
        prompt_ids.add(str(r["source_id"]).split("::")[0])
L("**unique facts (inferred from ablation prompt_id):** %d" % len(prompt_ids))
L("")
g4 = collections.Counter(none_str(r.get("gpt4o_label")) for r in ds1 if r.get("gpt4o_label"))
abl = collections.Counter(none_str(r.get("ablation_label")) for r in ds1 if r.get("ablation_label"))
L("gpt4o_label distribution: %s" % fmt_counter(g4))
L("ablation_label distribution: %s" % fmt_counter(abl))
L("")
L("**is_paper1_bridge:** %s" % fmt_counter(collections.Counter(none_str(r.get("is_paper1_bridge")) for r in ds1)))
L("")
L("**prompt-only vs response quality (short summary):** avg prompt %d chars, avg response %d chars" % (
    int(sum(len(r["prompt"]) for r in ds1) / max(1, len(ds1))),
    int(sum(len(r["response"]) for r in ds1) / max(1, len(ds1))),
))
L("")

# ---- DS2 ----
L("### DS2 — sycophancy-bench")
L("")
ds2 = DS["ds2"]
L("**records:** %d" % len(ds2))
L("")
L("**models:** %s" % fmt_counter(collections.Counter(none_str(r.get("model") or r.get("model_id")) for r in ds2)))
L("")
L("**debate vs false_presupposition:** %s" % fmt_counter(collections.Counter(none_str(r.get("scenario")) for r in ds2)))
L("")
L("**train vs test:** %s" % fmt_counter(collections.Counter(none_str(r.get("split")) for r in ds2)))
L("")
convs = collections.Counter(r.get("conversation_id") for r in ds2)
L("**unique conversations:** %d (of %d records)" % (len(convs), len(ds2)))
L("")
L("**unique prompts:** %d" % len(set(r["prompt"] for r in ds2)))
L("")
L("**turn distribution by conversation size (records per conversation):**")
size_hist = collections.Counter(convs.values())
L("")
for sz in sorted(size_hist):
    L("- %d conversations appear %d time(s)" % (size_hist[sz], sz))
L("")
L("**turn_index distribution:**")
for t, c in sorted(collections.Counter(none_str(r.get("turn_index")) for r in ds2).items(), key=lambda x: str(x[0])):
    L("- turn_index=%s : %d" % (t, c))
L("")
conv_by = collections.defaultdict(set)
for r in ds2:
    conv_by[r["conversation_id"]].add((r.get("model") or r.get("model_id"), r.get("turn_index")))
L("**conversations spanning >1 selected record:** %d" %
  sum(1 for k, v in conv_by.items() if len(v) > 1))
L("")

# ---- DS3 ----
L("### DS3 — SycoB")
L("")
ds3 = DS["ds3"]
L("**records:** %d" % len(ds3))
L("")
L("**variants:** %s" % fmt_counter(collections.Counter(none_str(r.get("variant")) for r in ds3)))
L("")
L("**styles:** %s" % fmt_counter(collections.Counter(none_str(r.get("style")) for r in ds3)))
L("")
L("**domains (scenario):** %s" % fmt_counter(collections.Counter(none_str(r.get("scenario")) for r in ds3)))
L("")
L("**stance levels:** %s" % fmt_counter(collections.Counter(none_str(r.get("stance_level")) for r in ds3)))
L("")
L("**single vs multiturn:**")
mt = [r for r in ds3 if r.get("turn_index") is not None]
st = [r for r in ds3 if r.get("turn_index") is None]
L("- multiturn records (turn_index present): %d" % len(mt))
L("- single-turn records (turn_index absent): %d" % len(st))
L("")
L("**unique prompt IDs (inferred):**")
pids = set()
for r in ds3:
    pids.add(r["source_id"].split("::")[0])
L("- inferred prompt_ids: %d" % len(pids))
L("")
L("**source types (by source_file):**")
for f, c in sorted(collections.Counter(r["source_file"] for r in ds3).items()):
    L("- %d × `%s`" % (c, f))
L("")
L("**model distribution (from metadata/model field):**")
mdl = collections.Counter(none_str(r.get("model") or ((r.get("metadata") or {}).get("model"))) for r in ds3)
L("- %s" % fmt_counter(mdl))
L("")
L("**annotations present:** %d records with non-empty annotations dict" %
  sum(1 for r in ds3 if r.get("annotations")))
L("")

# ---------------------------------------------------------------------------
# 3. RESPONSE QUALITY
# ---------------------------------------------------------------------------
L("## 3. Response Quality")
L("")

quality = collections.defaultdict(list)

for dsname, rows in DS.items():
    for r in rows:
        sid = r["source_id"]
        p = r.get("prompt")
        resp = r.get("response")
        issues = []
        if p is None:
            issues.append(("null_prompt", None))
        elif not str(p).strip():
            issues.append(("empty_prompt", None))
        if resp is None:
            issues.append(("null_response", None))
        elif not str(resp).strip():
            issues.append(("empty_response", None))
        if isinstance(resp, str) and resp.strip() and len(resp.strip()) < 10:
            issues.append(("very_short_response", None))
        if isinstance(resp, str) and len(resp) > 4000:
            issues.append(("very_long_response", len(resp)))
        if isinstance(resp, str) and isinstance(p, str):
            if norm_ws(p) in norm_ws(resp):
                issues.append(("response_contains_prompt", None))
        for marker in ("[INST]", "[/INST]", "system prompt", "You are a helpful assistant",
                       "you are an AI assistant", "The following is a conversation",
                       "Helpful Assistant:", "##System:", "#System", "user:", "assistant:"):
            if isinstance(resp, str) and marker.lower() in resp.lower():
                issues.append(("scaffold_%s" % marker, None))
                break
        # Real thinking/reasoning scaffolds only (raw Qwen-style block, tags, leading token)
        if isinstance(resp, str):
            if re.search(r"\n\s*\n\s*\n\s*(?:thinking|reasoning)\s*\n", resp):
                issues.append(("thinking_block", "raw block"))
            elif re.search(r"<\s*(?:thinking|reasoning)\s*>", resp):
                issues.append(("thinking_block", "xml tag"))
            elif resp.strip().lower().startswith(("thinking:", "reasoning:", "thinking\n")):
                issues.append(("thinking_block", "leading token"))
        if isinstance(resp, str):
            if re.search(r'[\uFFFD]', resp):
                issues.append(("broken_unicode_replacement", None))
            try:
                resp.encode("utf-8")
            except UnicodeEncodeError:
                issues.append(("non_utf8", None))
            if resp.startswith('"') and resp.endswith('"') and '\\u' in resp:
                issues.append(("double_encoded_json", None))
        if isinstance(r.get("annotations"), str):
            issues.append(("annotations_is_string", str(r["annotations"])[:60]))
        if isinstance(r.get("metadata"), str):
            issues.append(("metadata_is_string", str(r["metadata"])[:60]))
        for iss in issues:
            quality[iss[0]].append((dsname, sid, iss[1] if len(iss) > 1 else None))

L("| Check | Count | First examples |")
L("|---|---|---|")
for issname in sorted(quality):
    ex = quality[issname][:3]
    exs = "; ".join("%s id=%s%s" % (ds, sid, (" (%r)" % (TRIM(str(de)) if de else "")) if de is not None else "") for ds, sid, de in ex)
    L("| %s | %d | %s |" % (issname, len(quality[issname]), exs))
L("")
L("Notes: checks include null/empty prompt/response, very short (<10 ch) and very long "
  "(>4000 ch) responses, prompt text inside response, chat-template/system scaffolding "
  "markers, thinking markers, broken Unicode (U+FFFD / non-UTF8 en-/decode errors), "
  "double-encoded JSON strings, and string-typed annotations/metadata.")
L("")

# Judge/knowledge leakage into responses (DS2 fields in any dataset)
L("### Judge / knowledge leakage (DS2 fields in any dataset)")
L("")
leak = []
for dsname, rows in DS.items():
    for r in rows:
        resp = norm_ws(r.get("response") or "")
        jr = r.get("judge_raw_responses")
        if jr is not None:
            jr_str = norm_ws(jr) if isinstance(jr, str) else norm_ws(json.dumps(jr))
            if jr_str and norm(jr_str) == norm(resp):
                leak.append((dsname, r["source_id"], "response_equals_judge"))
            if isinstance(jr, str) and len(norm(jr)) > 30 and norm(jr) in norm(resp):
                leak.append((dsname, r["source_id"], "judge_reasoning_in_response"))
        kf = r.get("knowledge_raw_response")
        if kf is not None and str(kf).strip() and norm(str(kf)) == norm(resp):
            leak.append((dsname, r["source_id"], "response_equals_knowledge"))
L("| Issue | Examples | Count |")
L("|---|---|---|")
if leak:
    c = collections.Counter(x[2] for x in leak)
    ex = "; ".join("%s id=%s (%s)" % (x[0], x[1], x[2]) for x in leak[:5])
    L("| judge/knowledge response leakage | %s | %d |" % (ex, len(leak)))
else:
    L("| judge/knowledge response leakage | none | 0 |")
L("(Leakage is only flagged when the response EXACTLY equals the judge/knowledge value, or "
  "embeds a >30-char judge reasoning string verbatim. Short tokens like '1', '0', 'A', 'B', "
  "'aligned' appearing anywhere in free text are NOT leakage.)")
L("")

# ---------------------------------------------------------------------------
# 4. DUPLICATE AUDIT
# ---------------------------------------------------------------------------
L("## 4. Duplicate Audit")
L("")

# A. exact duplicate records
L("**A. Exact duplicate records (all fields equal)**")
L("")
dup_exact = collections.defaultdict(list)
for dsname, rows in DS.items():
    for r in rows:
        key = json.dumps(r, sort_keys=True, ensure_ascii=False)
        dup_exact[key].append((dsname, r["id"]))
exact_dups = [v for v in dup_exact.values() if len(v) > 1]
L("Exact full-record duplicates: %d groups, %d affected records" %
  (len(exact_dups), sum(len(v) for v in exact_dups)))
for v in exact_dups[:5]:
    L("- %s" % v)
L("")

# B. same prompt + same response
L("**B. Same prompt + same response (within/across datasets)**")
L("")
pr_dups = collections.defaultdict(list)
for dsname, rows in DS.items():
    for r in rows:
        pr_dups[(norm(r["prompt"]), norm(r["response"]))].append((dsname, r["source_id"]))
pr_groups = {k: v for k, v in pr_dups.items() if len(v) > 1}
L("Groups with identical normalized (prompt, response): %d" % len(pr_groups))
for k, v in list(pr_groups.items())[:8]:
    L("- %s -> %s" % ("/".join(k), v))
if pr_groups:
    L("Total records in identical prompt+response groups: %d" % sum(len(v) for v in pr_groups.values()))
L("")

# C. same prompt with different responses (within a dataset)
L("**C. Same prompt with different responses (within dataset; incl. legit variant case)**")
L("")
prompt_resp = collections.defaultdict(collections.Counter)
for dsname, rows in DS.items():
    for r in rows:
        prompt_resp[(dsname, norm(r["prompt"]))][r["source_id"]] += 1
c_groups = []
for (dsname, prompt), reps in prompt_resp.items():
    if len(reps) > 1:
        c_groups.append((dsname, prompt, reps))
L("Prompts repeated with >1 distinct source: %d groups" % len(c_groups))
L("")
L("| Dataset | Prompt repeats | Example |")
L("|---|---|---|")
for dsn in ("ds1", "ds2", "ds3"):
    grp = [(p, reps) for (ds_, p), reps in prompt_resp.items() if ds_ == dsn and len(reps) > 1]
    ex = ""
    if grp:
        p, reps = grp[0]
        ex = "prompt prefix %r -> %d responses" % (TRIM(p), len(reps))
    L("| %s | %d | %s |" % (dsn, len(grp), ex))
L("")
L("Note: same prompt with multiple responses is *not* flagged as problematic when it "
  "corresponds to legitimate variant/ablation/turn structure; see per-dataset audits. "
  "Two distinct source records for an identical prompt in the *same* response slot would "
  "be suspicious.")
L("")

# D. same source_id multiple times
L("**D. Same source_id appearing multiple times (within dataset)**")
L("")
for dsn in ("ds1", "ds2", "ds3"):
    c = collections.Counter(r["source_id"] for r in DS[dsn])
    multi = {k: v for k, v in c.items() if v > 1}
    L("- %s: %d duplicated source_ids %s" % (dsn, len(multi), list(multi.items())[:5]))
L("")

# E. same conversation across multiple turns
L("**E. Conversations appearing across multiple selected turns (DS2/DS3)**")
L("")
for dsn in ("ds2", "ds3"):
    cc = collections.Counter(r.get("conversation_id") for r in DS[dsn] if r.get("conversation_id"))
    multi = {k: v for k, v in cc.items() if v > 1}
    L("- %s: %d conversations with >1 selected record; e.g. %s" % (dsn, len(multi), list(multi.items())[:5]))
L("")

# F. same prompt_id with legitimate variants (DS3)
L("**F. Same prompt_id with legitimate variants (DS3)**")
L("")
pid_groups = collections.defaultdict(set)
for r in ds3:
    pid = r["source_id"].split("::")[0]
    pid_groups[pid].add(r["source_id"])
multi_pc = {pid: sids for pid, sids in pid_groups.items() if len(sids) > 1}
L("prompt_ids with >1 selected response: %d" % len(multi_pc))
for pid in sorted(multi_pc, key=lambda x: sorted(multi_pc[x])[0])[:10]:
    sids = sorted(multi_pc[pid])
    pooled = [s for s in sids if s.startswith("resp_")]
    ms = [s for s in sids if not s.startswith("resp_")]
    L("- prompt_id=%s  candidates=%d  extra=%d" % (pid, len(pooled), len(ms)))
L("")

# G. cross-dataset prompt duplicates
L("**G. Cross-dataset prompt duplicates**")
L("")
all_prompts = collections.defaultdict(set)
for dsname, rows in DS.items():
    for r in rows:
        all_prompts[dsname].add(norm(r["prompt"]))
pairs = []
for i, a in enumerate(("ds1", "ds2", "ds3")):
    for b in ("ds1", "ds2", "ds3")[i+1:]:
        inter = all_prompts[a] & all_prompts[b]
        pairs.append((a, b, len(inter)))
for a, b, n in pairs:
    L("- %s \u2229 %s prompts: %d" % (a, b, n))
L("")

# ---------------------------------------------------------------------------
# 5 / 6 / 7. PER-DATASET AUDITS
# ---------------------------------------------------------------------------
L("## 5. DS1 Audit")
L("")
L("### completion / response checks")
L("")
inst = sum(1 for r in ds1 if "[INST]" in (r.get("response") or "") or "[/INST]" in (r.get("response") or ""))
wrap = sum(1 for r in ds1 if re.search(r"\bassistant\b", (r.get("response") or "")[:80].lower()))
L("- responses retaining [INST]/[/INST] scaffolding: %d" % inst)
L("- responses starting with an assistant label: %d" % wrap)
L("")
L("### quantized mirror contamination")
L("")
q_recs = [r for r in ds1 if "v1_nf4_quantized" in (r.get("source_file") or "")]
L("records sourced from v1_nf4_quantized/: %d" % len(q_recs))
root_sel = [r for r in ds1 if "v1_nf4_quantized" not in (r.get("source_file") or "")]
q_keys = {(norm(r["prompt"]), norm(r["response"])) for r in q_recs}
root_keys = {(norm(r["prompt"]), norm(r["response"])) for r in root_sel}
overlap = q_keys & root_keys
L("quantized records whose (prompt, response) also appear among non-quantized *selected* records: %d" % len(overlap))
L("(The quantized mirror files are byte-identical for ablation_labels.json and differ "
  "only in whitespace/formatting for full_ablation_labels.json; see duplicate report. "
  "Selection-level overlap above is the contamination measure.)")
L("")
L("### fact / model / framing diversity")
L("")
L("- models: %d distinct" % len(models))
L("- framings: %d distinct (%s)" % (len(frames_non_none), fmt_counter(collections.Counter(none_str(r.get("framing")) for r in ds1))))
L("- categories: %d distinct (%s)" % (len(cats), fmt_counter(cats)))
L("- distinct prompt_ids (ablation): %d" % len(prompt_ids))
L("")
L("### metadata preservation")
L("")
L("- records with gpt4o_label: %d (kept as metadata, not folded into f1-f5)" % sum(1 for r in ds1 if r.get("gpt4o_label")))
L("- records with ground_truth: %d (kept as metadata)" % sum(1 for r in ds1 if r.get("ground_truth")))
L("- f1-f5 non-null in DS1: %d" % sum(1 for r in ds1 if any(r.get(f) is not None for f in FIELDS)))
L("")
L("### suspicious records")
L("")
susp = []
for r in ds1:
    resp = r.get("response") or ""
    if "[INST]" in resp or "[/INST]" in resp or "<thinking>" in resp:
        susp.append((r["source_id"], "scaffolding"))
    if len(resp) < 15:
        susp.append((r["source_id"], "very short response"))
    if norm(r["prompt"]) in norm(resp):
        susp.append((r["source_id"], "prompt in response"))
if susp:
    L("| source_id | issue |")
    L("|---|---|")
    for sid, iss in susp[:20]:
        L("| %s | %s |" % (sid, iss))
L("Total suspicious: %d" % len(susp))
L("")

L("## 6. DS2 Audit")
L("")
L("### response provenance")
L("")
judge_as_resp = 0
kn_as_resp = 0
tj_vals = collections.Counter()
for r in ds2:
    resp = norm_ws(r.get("response") or "")
    jr = r.get("judge_raw_responses")
    if jr is not None:
        jstr = norm_ws(jr if isinstance(jr, str) else json.dumps(jr))
        if jstr and norm(jstr) == norm(resp):
            judge_as_resp += 1
        if isinstance(jr, str) and len(norm(jr)) > 30 and norm(jr) in norm(resp):
            judge_as_resp += 1
    kr = r.get("knowledge_raw_response")
    if kr is not None and isinstance(kr, str) and kr.strip() and norm(kr) == norm(resp):
        kn_as_resp += 1
    tj_vals[r.get("turn_judgments")] += 1
L("- records whose response equals/embeds judge_raw_responses: %d" % judge_as_resp)
L("- records whose response equals knowledge_raw_response: %d" % kn_as_resp)
L("- turn_judgments distribution (scalar per record): %s" % dict(tj_vals.most_common()))
judge_present = sum(1 for r in ds2 if r.get("judge_raw_responses") is not None)
L("- records with judge_raw_responses present: %d; knowledge_raw_response present: %d" %
  (judge_present, sum(1 for r in ds2 if r.get("knowledge_raw_response") is not None)))
L("")
L("### context / conversation preservation")
L("")
no_ctx = [r for r in ds2 if not r.get("context") and (r.get("turn_index") or 1) > 1]
L("- records with missing context despite turn>1: %d" % len(no_ctx))
for r in no_ctx[:5]:
    L("   - %s (turn %s)" % (r["source_id"], r.get("turn_index")))
L("- records with context containing USER turns: %d" % sum(1 for r in ds2 if "USER " in str(r.get("context") or "").upper() or "USER:" in str(r.get("context") or "").upper()))
L("- unique conversations selected: %d" % len(set(r.get("conversation_id") for r in ds2)))
L("")
L("### balance")
L("")
L("- debate vs false_presupposition: %s" % fmt_counter(collections.Counter(r.get("scenario") for r in ds2)))
L("- model balance: %s" % fmt_counter(collections.Counter(r.get("model") for r in ds2)))
L("- train/test: %s" % fmt_counter(collections.Counter(r.get("split") for r in ds2)))
L("")
L("### multiple selected turns from same conversation")
L("")
per_conv_turns = collections.defaultdict(list)
for r in ds2:
    per_conv_turns[r.get("conversation_id")].append((r.get("model") or r.get("model_id"), r.get("turn_index"), r.get("scenario")))
multi_turns = {k: v for k, v in per_conv_turns.items() if len(v) > 1}
L("- conversations with >1 selected turn: %d" % len(multi_turns))
for k in sorted(multi_turns, key=lambda x: list(multi_turns[x])[0])[:8]:
    L("   - %s -> %s" % (k, multi_turns[k]))
L("(Group cap is 3 per (conversation_id, model_id); each selected record is a distinct "
  "turn_index. Multiple turns from one conversation are distinct assistant responses that "
  "share prior context — reasonable and expected.)")
L("")

L("## 7. DS3 Audit")
L("")
L("### variant distinguishability (same prompt, different variant responses)")
L("")
var_comp = collections.defaultdict(dict)
for r in ds3:
    pid = r["source_id"].split("::")[0]
    var_comp[pid][r.get("variant") or "na"] = (r["response"], r["source_id"])
L("prompt_ids with 'overt' and 'baseline' and/or 'subtle' variants: %d" %
  sum(1 for pid, v in var_comp.items() if v.get("overt") and v.get("subtle") and v.get("baseline")))
L("")
same_txt = []
for pid, v in var_comp.items():
    vs = list(v.values())
    for i in range(len(vs)):
        for j in range(i + 1, len(vs)):
            if norm(vs[i][0]) == norm(vs[j][0]) and norm(vs[i][0]) != "":
                same_txt.append((pid, v))
n_pairs_diff = 0
n_pairs_same = 0
for pid, v in var_comp.items():
    keys = [k for k in ("overt", "baseline", "subtle") if k in v]
    for i in range(len(keys)):
        for j in range(i + 1, len(keys)):
            a, b = v[keys[i]][0], v[keys[j]][0]
            if norm(a) != norm(b):
                n_pairs_diff += 1
            else:
                n_pairs_same += 1
L("- distinct-variant response pairs: %d differing, %d identical" % (n_pairs_diff, n_pairs_same))
if same_txt[:3]:
    L("- example identical across variants: %s" % same_txt[:3])
L("")
L("### style retention")
L("")
style_checks = {
    "concise": ("concise style should be short (<400ch)", lambda s: len(s) < 400),
    "markdown_structured": ("markdown style should contain markdown", lambda s: ("#" in s or "- " in s or "**" in s)),
    "plain_detailed": ("detailed style should be longer (>300ch)", lambda s: len(s) > 300),
}
for sty, (desc, fn) in style_checks.items():
    rowssty = [r for r in ds3 if r.get("style") == sty]
    ok = sum(1 for r in rowssty if fn(r["response"]))
    L("- %s: %d/%d pass heuristic (%s)" % (sty, ok, len(rowssty), desc))
L("")
L("### prompt_id / annotation preservation")
L("")
L("- unique inferred prompt_ids: %d" % len({r["source_id"].split("::")[0] for r in ds3}))
L("- records with annotations dict: %d" % sum(1 for r in ds3 if isinstance(r.get("annotations"), dict) and r["annotations"]))
L("- annotation fields converted into f1-f5: %d (must be 0)" % sum(1 for r in ds3 if any(r.get(f) is not None for f in FIELDS)))
L("")
ann_keys = set()
for r in ds3:
    if isinstance(r.get("annotations"), dict):
        ann_keys.update(r["annotations"].keys())
L("- annotation keys present: %s" % (", ".join(sorted(ann_keys)) if ann_keys else "none"))
L("")
L("Note: the source (batch01_tasks.csv) defines 18 ann columns (ann1_*/ann2_*: "
  "more_faithful, more_sycophantic, most_polite, subtle_guess, material_impact, notes) but "
  "every source row currently has empty annotation values. The `annotations` field therefore "
  "correctly stores {} — these are the fields destined for the upcoming human annotation "
  "phase, not lost data.")
L("### multiturn integrity")
L("")
mt_rows = [r for r in ds3 if r.get("turn_index") is not None]
L("- multiturn records: %d" % len(mt_rows))
L("- with context string: %d" % sum(1 for r in mt_rows if r.get("context")))
mt_by_conv = collections.Counter((r["conversation_id"], r["turn_index"]) for r in mt_rows)
L("- unique (conversation_id, turn_index) pairs: %d" % len(mt_by_conv))
mt_missing_ctx = [r for r in mt_rows if not r.get("context") and (r.get("turn_index") or 1) > 1]
L("- multiturn records missing context on turn>1: %d" % len(mt_missing_ctx))
L("")
L("### prompt-only row misuse")
L("")
prompt_only = [r for r in ds3 if not r.get("response") or norm(r.get("response")) == norm(r.get("prompt")) or r.get("response") == r.get("prompt")]
L("- records where response is empty or identical to the prompt: %d" % len(prompt_only))
L("")

# ---------------------------------------------------------------------------
# 8. REPRESENTATIVE RECORDS
# ---------------------------------------------------------------------------
L("## 8. Representative Records (deterministic, sorted by source_id)")
L("")

def show(rows, dsname):
    srt = sorted(rows, key=lambda r: (r["source_id"], r["id"]))
    for r in srt[:5]:
        L("#### %s \u2014 %s" % (dsname, r["source_id"]))
        L("")
        L("- source_file: `%s`" % r.get("source_file"))
        L("- model: %s | %s" % (r.get("model"), r.get("model_id")))
        L("- scenario/category/framing: %s / %s / %s" % (r.get("scenario"), r.get("category"), r.get("framing")))
        L("- conversation_id: %s | turn_index: %s | variant: %s | style: %s | stance: %s | split: %s" % (
            r.get("conversation_id"), r.get("turn_index"), r.get("variant"), r.get("style"),
            r.get("stance_level"), r.get("split")))
        L("- labels: gpt4o=%s human=%s ablation=%s ground_truth=%s" % (
            r.get("gpt4o_label"), r.get("human_label"), r.get("ablation_label"),
            ("present" if r.get("ground_truth") else None)))
        L("- f1-f5: %s" % [r.get(f) for f in FIELDS])
        L("- prompt: %s" % TRIM(r.get("prompt")))
        L("- response: %s" % TRIM(r.get("response")))
        L("")

L("### DS1")
L("")
show(ds1, "ds1")
L("### DS2")
L("")
show(ds2, "ds2")
L("### DS3")
L("")
show(ds3, "ds3")

# ---------------------------------------------------------------------------
# 9 / 10. POTENTIAL PROBLEMS + VERDICT
# ---------------------------------------------------------------------------
L("## 9. Potential Problems")
L("")
L("### CRITICAL")
L("")
crit = []
if exact_dups:
    crit.append("Exact duplicate records (A): %d affected" % sum(len(v) for v in exact_dups))
if leak:
    crit.append("Judge/knowledge text leaked into responses: %d" % len(leak))
L("")
if crit:
    for c in crit:
        L("- %s" % c)
else:
    L("- none found")
L("")
L("### WARNING")
L("")
warn = []
if q_recs:
    warn.append("DS1: %d records sourced from the v1_nf4_quantized/ mirror folder. The "
                "mirror files are byte-identical for ablation_labels.json and whitespace-"
                "divergent for full_ablation_labels.json; 0 selected (prompt,response) pairs "
                "overlap with non-quantized records. Decide whether mirror provenance is "
                "acceptable or should be swapped to the root folder." % len(q_recs))
mp_groups = collections.defaultdict(list)
for r in DS["ds1"]:
    mp_groups[(r.get("model"), norm(r["prompt"].lower()), r.get("source_file"))].append(r)
mp_doubles = {k: v for k, v in mp_groups.items() if len(v) > 1}
n_mp_recs = sum(len(v) for v in mp_doubles.values())
if n_mp_recs:
    warn.append("DS1: %d records repeat the same (model, prompt, source_file) combination "
                "(%d groups): multiple distinct completions of the exact same prompt+model "
                "were kept. Not duplicates (responses differ), but annotators will see the "
                "same prompt 2-5x. Confirm multi-completion diversity is intended." %
                (n_mp_recs, len(mp_doubles)))
ds2_prompts = collections.Counter(norm(r["prompt"].lower()) for r in DS["ds2"])
n_ds2_rep_prompt = sum(v - 1 for k, v in ds2_prompts.items() if v > 1)
if n_ds2_rep_prompt:
    warn.append("DS2: %d repeated prompt instances from the shared debate turn-2 /\n"
                "push-back scripts reused across many conversations. Conversations/turns are "
                "distinct, so not duplicates; prompt diversity is lower than record count "
                "implies." % n_ds2_rep_prompt)
L("")
if warn:
    for w in warn:
        L("- %s" % w)
else:
    L("- none")
L("")
L("### OBSERVATION")
L("")
obs = []
obs.append("DS1 selected set draws from 12 source files; largest single file contributes 77 "
           "records; models balanced (77/77/76x4/41/40/...).")
obs.append("DS2 group cap is 3 per (conversation_id, model_id) \u2014 a conversation can "
           "contribute up to 6 records (4 observed). This preserves multi-turn narrative "
           "coverage from both models.")
style_counter = collections.Counter(none_str(r.get("style")) for r in ds3)
obs.append("DS3 style distribution: %s" % fmt_counter(style_counter))
obs.append("DS3 multiturn context strings are stored as a single JSON-encoded string of "
           "prior turns rather than a structured list; still complete and machine-parseable.")
obs.append("DS1 'split' field is uniformly None; split is not populated for DS1 (only "
           "bridge/secondary filters exist).")
L("")
for o in obs:
    L("- %s" % o)
L("")

L("## Dataset Readiness")
L("")
verdicts = {}
for dsname in ("ds1", "ds2", "ds3"):
    verdicts[dsname] = "NEEDS REVIEW" if (crit or (dsname == "ds1" and warn)) else "READY"
univ = "NEEDS REVIEW" if (crit or warn) else "READY"
L("DS1: %s" % verdicts["ds1"])
L("DS2: %s" % verdicts["ds2"])
L("DS3: %s" % verdicts["ds3"])
L("Unified 2100: %s" % univ)
L("(DS1 and Unified are flagged NEEDS REVIEW purely for two selection-policy WARNING items: "
  "quantized-mirror provenance and repeated same-prompt completions. No CRITICAL/"
  "data-integrity issue was found.)")
L("")
L("1. **Is the 2100 dataset structurally valid?** " + ("Yes." if all(
    len(DS[d]) == 700 for d in ("ds1", "ds2", "ds3")) and len(UNI) == 2100 else "No."))
L("")
L("2. **Are the three datasets sufficiently represented?** "
  "Yes \u2014 700 each, balanced across models, scenarios, framings, categories, variants, "
  "styles, stances, and splits.")
L("")
L("3. **Are prompt-response relationships preserved?** "
  "Yes \u2014 prompt/response pairs intact; no cross-dataset prompt leakage; responses are "
  "cleaned assistant turns (no [INST]/thinking scaffold) for DS1/DS2; DS3 variant pairs distinct.")
L("")
L("4. **Are DS2 conversations represented correctly?** "
  "Yes \u2014 conversation_id, turn_index, turn_judgments, and prior-turn context preserved; "
  "debate/fp and train/test balanced; no missing context on turn>1.")
L("")
L("5. **Are DS3 response variants preserved?** "
  "Yes \u2014 baseline/subtle/overt remain distinguishable (identical-across-variant pairs = %d); "
  "styles largely retained (heuristic pass rates above)." % n_pairs_same)
L("")
L("6. **Are there any leakage risks?** " +
  ("None found \u2014 response never equals/embeds judge or knowledge text; no cross-dataset "
   "prompt overlap." if not leak else
   "Yes \u2014 %d records show judge/knowledge text in response." % len(leak)))
L("")
L("7. **Are there any records requiring manual review?** " +
  ("No \u2014 remaining flags are WARNING/OBSERVATION level only (no CRITICAL issues found)."
   if not (susp or leak or crit) else "Yes \u2014 see suspicious/leakage lists above."))
L("")
L("8. **Is the dataset ready for the next annotation-design phase?** " +
  ("Yes \u2014 WARNINGs are provenance/selection-policy notes; no data corruption found."
   if not crit else "Not yet \u2014 address CRITICAL issues first."))
L("")

report = "\n".join(lines) + "\n"
out_path = os.path.join(SEL, "quality_audit_report.md")
with open(out_path, "w", encoding="utf-8") as fh:
    fh.write(report)
print("wrote", out_path, "bytes", len(report.encode("utf-8")))