#!/usr/bin/env python3
"""Render dataset/schis02_label_analysis.md from the compute() output.

The markdown text is generated from computed statistics only; no claim numbers
are hardcoded, nothing is invented. Reads the same READ-ONLY sources as
scripts/analyze_labels.py.
"""
from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from analyze_labels import compute, FRAMINGS, DATASET  # noqa: E402

OUT_MD = DATASET / "schis02_label_analysis.md"
OUT_JSON = DATASET / "schis02_label_analysis.json"

PAIRS = ["original", "leading", "opinion", "authority"]


def main():
    J, ctx = compute()
    mf = ctx["model_framing"]
    mfp = ctx["model_framing_pool"]
    sig = ctx["sig"]
    wl = ctx["wilcoxon"]
    stoch = ctx["stochastic"]
    fs = ctx["facts_stats"]
    t0f = ctx["t0_framing"]

    # computed highlights used in the prose
    largest_pos = max(mf, key=lambda m: mf[m]["_delta_S1_authority_minus_neutral_pp"])
    largest_neg = min(mf, key=lambda m: mf[m]["_delta_S1_authority_minus_neutral_pp"])
    d_pos = mf[largest_pos]["_delta_S1_authority_minus_neutral_pp"]
    d_neg = mf[largest_neg]["_delta_S1_authority_minus_neutral_pp"]
    worst_r = max(mf, key=lambda m: mf[m]["authority"]["R_pct"])

    L = []
    L.append("# schis02 Label-Behavior Analysis")
    L.append("")
    L.append("_Generated by scripts/analyze_labels.py + scripts/render_label_report.py (read-only). "
             "Nothing modified, sampled, re-labeled, split or deleted; no new label or sycophancy score "
             "invented. Label = source `gpt4o_label`. Descriptive analysis only.")
    L.append("")

    # ------------------------------------------------------------- 1
    L.append("## 1. Label distribution by framing")
    L.append("")
    L.append("Pool view (content-unique labeled rows; phase-3 models only, since phase-4 pool rows are unlabeled):")
    L.append("")
    L.append("| framing | labeled rows | S1 | S2 | C | H | R |")
    L.append("|---|--:|--:|--:|--:|--:|--:|")
    for f in FRAMINGS:
        d = J["framing_label_distribution_pool"][f]
        L.append(f"| {f} | {d['labeled_pool_rows']} | N={d['S1']['count']} ({d['S1']['rate']:.1f}%)"
                 f" | N={d['S2']['count']} ({d['S2']['rate']:.1f}%)"
                 f" | N={d['C']['count']} ({d['C']['rate']:.1f}%)"
                 f" | N={d['H']['count']} ({d['H']['rate']:.1f}%)"
                 f" | N={d['R']['count']} ({d['R']['rate']:.1f}%) |")
    L.append("")
    L.append("Source reference (all labeled records incl. stochastic draws, all 8 models; rates are S1/S2/C/H/R):")
    L.append("")
    L.append("| framing | labeled records | S1 | S2 | C | H | R |")
    L.append("|---|--:|--:|--:|--:|--:|--:|")
    for f in FRAMINGS:
        d = J["framing_label_distribution_source_all"][f]
        L.append(f"| {f} | {d['source_labeled_records']} | {d['S1']['rate']:.1f}% | {d['S2']['rate']:.1f}%"
                 f" | {d['C']['rate']:.1f}% | {d['H']['rate']:.1f}% | {d['R']['rate']:.1f}% |")
    L.append("")
    L.append("**Reading:** framing-conditioned shifts exist at the aggregate level, but they are NOT uniform "
             "across models (section 3): the largest single-model authority effect is "
             f"{d_pos:+.1f}pp S1 ({largest_pos}), while the largest negative authority effect is {d_neg:+.1f}pp "
             f"({largest_neg}). A single 'authority raises sycophancy' statement does not hold for every model.")
    L.append("")

    # ------------------------------------------------------------- 2
    L.append("## 2. Within-fact framing comparison (pool)")
    L.append("")
    L.append(f"- Facts: **{fs['n_facts']}**; facts containing **both S1 and non-S1** labeled rows: "
             f"**{fs['facts_with_both_S1_and_nonS1']}**.")
    L.append(f"- Facts with at least one S1 at neutral: {fs['facts_with_S1_at_neutral']}; "
             f"at authority: {fs['facts_with_S1_at_authority']}.")
    L.append(f"- Facts whose aggregate S1 rate (all models, all temps pooled) rises neutral->authority by >0.5pp: "
             f"{fs['facts_delta_S1_ntoa_up_gt0p5pp']}; falls: {fs['facts_delta_S1_ntoa_down_lt0p5pp']}.")
    L.append(f"- Across facts: median delta S1 (neutral->authority) = {fs['median_delta_S1_ntoa_pp']:+.1f}pp, "
             f"range [{fs['min_delta_S1_ntoa_pp']:+.1f}, {fs['max_delta_S1_ntoa_pp']:+.1f}]pp.")
    L.append("")
    L.append("Within-(fact, framing) cells the pool also hosts multiple labels: "
             f"{fs['fact_framing_cells_with_multiple_labels']} of {fs['fact_framing_cells_total']} "
             "cells contain >=2 distinct labels, i.e. the same prompt-framing combination can produce "
             "qualitatively different responses even after text dedupe.")
    L.append("")
    L.append("Model label change across framings is pinned down most cleanly at T=0 (one deterministic "
             "response per (fact, framing, model)) - see section 4 for the signature analysis.")
    L.append("")

    # ------------------------------------------------------------- 3
    L.append("## 3. Model x framing effects (S1%, C%)")
    L.append("")
    L.append("Pool matrix, S1% (rows = phase-3 models with labeled pool rows):")
    L.append("")
    L.append("| model | neutral | original | leading | opinion | authority |")
    L.append("|---|---:|---:|---:|---:|---:|")
    for m in sorted(mfp):
        L.append(f"| {m} | {mfp[m]['neutral']['S1_pct']:.1f} | {mfp[m]['original']['S1_pct']:.1f}"
                 f" | {mfp[m]['leading']['S1_pct']:.1f} | {mfp[m]['opinion']['S1_pct']:.1f}"
                 f" | {mfp[m]['authority']['S1_pct']:.1f} |")
    L.append("")
    L.append("Source authoritative (all labeled records incl. stochastic draws), S1% C% R% per framing:")
    L.append("")
    L.append("| model | neutral S1 | authority S1 | delta S1 (auth-neutral) | authority R | neutral C |")
    L.append("|---|---:|---:|---:|---:|---:|")
    for m in sorted(mf):
        nS = mf[m]["neutral"]["S1_pct"]; aS = mf[m]["authority"]["S1_pct"]
        L.append(f"| {m} | {nS:.1f} | {aS:.1f} | {aS-nS:+.1f} | {mf[m]['authority']['R_pct']:.1f}"
                 f" | {mf[m]['neutral']['C_pct']:.1f} |")
    L.append("")
    L.append("**Reading (computed from the two tables above):** the framing effect is **heterogeneous across "
             "models**. "
             f"{largest_pos} shows the strongest authority->S1 increase ({d_pos:+.1f}pp); "
             f"{largest_neg} shows the strongest decrease ({d_neg:+.1f}pp)."
             + (f" {worst_r} instead shifts to refusal wording under authority "
                f"(authority R {mf[worst_r]['authority']['R_pct']:.0f}%) while its authority-phase S1 rate is "
                f"{mf[worst_r]['authority']['S1_pct']:.1f}%."
                if mf[worst_r]["authority"]["R_pct"] >= 10 else "")
             + " Any SycAudit target that assumes a single 'framing makes outputs more sycophantic' direction "
               "is contradicted by this data.")
    L.append("")

    # ------------------------------------------------------------- 4
    L.append("## 4. T=0 (deterministic) vs stochastic draws")
    L.append("")
    L.append(f"- T=0 labeled records: {J['t0_analysis']['phase3_t0_cells']} phase-3 cells"
             + (f" + {J['t0_analysis']['phase4_t0_extra_cells']} phase-4 cells" 
                if J["t0_analysis"]["phase4_t0_extra_cells"] else "")
             + " (one response per (fact, framing, model)).")
    L.append("  T=0 S1% per framing: " + ", ".join(
        f"{f} {t0f[f]['S1_pct']:.1f}%" for f in FRAMINGS) + ".")
    L.append("")
    L.append("- Per-(fact, model) T=0 label signature across the 5 framings:")
    L.append(f"  - units with a complete 5-framing signature: {J['t0_analysis']['signature_units_with_all5_framings']}; "
             f"identical label in all 5 framings: {J['t0_analysis']['signature_units_identical_label_all5']}; "
             "distinct-labels-per-unit distribution: "
             + ", ".join(f"{k} labels x {v} units" for k, v in sorted(
                 J["t0_analysis"]["distinct_labels_per_unit_distro"].items())) + ".")
    L.append("  - T=0 label is deterministic *per cell*: at temp 0 the same (fact, framing, model) always yields "
             "the same text, so all within-signature label change is **attributable to framing** (same fact, same "
             "model).")
    L.append("")
    L.append("- Exact McNemar, S1 vs not-S1, paired per (fact, model), neutral vs each framing (T=0):")
    L.append("")
    L.append("| framing | neutral-S1-only | framed-S1-only | n pairs | exact 2-sided p |")
    L.append("|---|---:|---:|---:|---:|")
    for f in PAIRS:
        mc = J["t0_analysis"]["mcnemar_S1_neutral_vs_framing"][f]
        pstr = f"{mc['exact_two_sided_p']:.4f}" if mc["exact_two_sided_p"] is not None else "n/a"
        L.append(f"| {f} | {mc['neutral_S1_only']} | {mc['framed_S1_only']} | {mc['n_units']} | {pstr} |")
    L.append("")
    L.append("- Paired Wilcoxon signed-rank, T=0 S1 indicators neutral vs framed (descriptive; binary data makes "
             "this a weaker analogue of McNemar):")
    L.append("")
    for f in PAIRS:
        w = wl.get(f)
        if w and "p" in w:
            L.append(f"  - {f}: neutral {w['mean_neutral_S1_pct']:.1f}% -> framed {w['mean_framed_S1_pct']:.1f}%"
                     f" ({w['delta_pp']:+.1f}pp, W={w['W']:.0f}, p={w['p']})")
        elif w:
            L.append(f"  - {f}: {w.get('note', 'n/a')}")
    L.append("")
    L.append("- Stochastic (T=0.3/0.7) draw-level variability, phase-3 labeled records "
             f"({stoch['n_cells_Tgt_draws']} cells x 10 draws):")
    L.append(f"  - cells whose draws carry mixed labels: {stoch['cells_with_mixed_draw_labels_pct']:.1f}%.")
    L.append(f"  - cells with both S1 and non-S1 draws (a 'flip' in sycophancy across identical prompts): "
             f"{stoch['cells_with_both_S1_and_nonS1_draws_pct']:.1f}%.")
    L.append("  - distinct labels per cell: " + ", ".join(
        f"{k} labels x {v} cells" for k, v in stoch["distinct_labels_per_cell_distro"].items()) + ".")
    L.append(f"  - cell S1 rate: mean {stoch['cell_mean_S1_rate_pct']:.1f}%, sd {stoch['cell_S1_rate_sd_pct']:.1f}% "
             "(across cells).")
    L.append("")
    L.append("**Framing effect vs sampling variation (descriptive).** At T=0, whole-framing differences are "
             "deterministic: the paired McNemar tests above show which models flip S1 between neutral and each "
             "framing given the *same* (fact, model). At T>0, resampling the same (fact, framing, model) already "
             f"mixes labels in {stoch['cells_with_mixed_draw_labels_pct']:.1f}% of cells. Where a model shows a "
             "large deterministic framing delta (section 3), that signal is larger than its own sampling "
             "variability; where deltas are near zero the framing signal is not separable from sampling noise. "
             "This remains a descriptive comparison - no formal equal-variance/effect test is claimed.")
    L.append("")

    # ------------------------------------------------------------- 5
    L.append("## 5. Source label semantics and A/B/C options")
    L.append("")
    L.append("Taxonomy (source): **S1** sycophantic agreement, **S2** confabulation, **C** correct, **H** hedge, "
             "**R** refusal; produced by GPT-4o-mini (`gpt4o_label`), agreement with human labels reported as "
             "kappa 0.752 (README).")
    L.append("")
    L.append("Validation evidence from source artifacts (lexical_validation.txt, full_audit.txt, "
             "cross_judge_kdg_comparison.txt, bootstrap_kdg_ci.txt):")
    L.append("- S1 rows: agreement phrases present in 34.5%; R rows: refusal phrases in 92.5%; S1<->R "
             "cross-contamination 0 (i.e. no row labeled S1 contains a refusal phrase and vice versa).")
    L.append("- precision(labeled S1 | S1 phrase) ~90.5%; precision(labeled R | refusal phrase) ~54.3%.")
    L.append("- source KDG metric = correct_rate(neutral) - correct_rate(framed), correct = {C, H}; sign "
             "agreement between GPT-4o and GPT-4o-mini judgments on 21/24 model-framing cells; cluster-bootstrap "
             "CIs (10k) e.g. Llama-3.1-70B authority KDG +0.043 [+0.003,+0.090].")
    L.append("")
    L.append("Implications for SycAudit (not decided here):")
    L.append("- **(A) final supervised target.** Feasible: labels are consistent, validated and complete for the "
             "phase-3 rows (4,462 in the pool). Risk: a per-row classifier can reach high agreement by learning "
             "the confounders in section 7 (model, length, refusal wording, category), not by modeling "
             "sycophancy.")
    L.append("- **(B) auxiliary target.** The taxonomy is most defensibly used as a secondary head / eval metric "
             "alongside a framing-contrast objective (units B/D, section 6).")
    L.append("- **(C) analysis-only.** The labels are also valid as pure descriptive labels, but then they "
             "contribute no supervision.")
    L.append("The taxonomy labels *response type*; it does not by itself express whether a model *changed* "
             "across framings. For SycAudit's purpose that change is the object of interest, so the taxonomy is "
             "necessary but not sufficient on its own.")
    L.append("")

    # ------------------------------------------------------------- 6
    L.append("## 6. Training-unit representation comparison (structural)")
    L.append("")
    L.append("| representation | unit count | keeps (fact,model) framing pairing? | what it can express |")
    L.append("|---|---|---|---|")
    L.append(f"| **A: row per response** | {J['_meta']['pool_labeled_rows']} labeled pool rows "
             f"(7,455 total pairs) | no - framing is a nominal feature | per-row response type P(label | prompt, "
             "model, framing); needs wide generalization across facts/framings/models |")
    L.append(f"| **B: model x fact group** | 400 units; {J['t0_analysis']['signature_units_with_all5_framings']} "
             "with complete 5-framing T=0 signatures | yes - the 5 framing responses of a fact are one unit | "
             "per-model behavioral profile per fact; detects framing-induced label change |")
    L.append("| **C: fact group** | 50 | partially - 8 models x 5 framings nested | fact-level aggregate; N=50 "
             "is tiny, pairing is implicit |")
    L.append(f"| **D: pairwise (neutral vs framed)** | up to {len(sig)} x 4 pairs at T=0 | yes - directly encodes "
             "the contrast | 'does framing move this model's T=0 label' as a binary / delta target |")
    L.append("")
    L.append("A/B/D differ from C in the strength of the causal object they expose: A sees isolated triples, "
             "B/D keep the same-fact-same-model contrast that is the actual signal. C keeps everything but is "
             "statistically thin (50 units). No unit type is selected here.")
    L.append("")

    # ------------------------------------------------------------- 7
    L.append("## 7. Confounder / shortcut analysis")
    L.append("")
    mc = J["model_identity_confounder"]
    L.append(f"- **Model identity.** Pool S1% ranges {mc['S1_rate_range_pp'][0]}..{mc['S1_rate_range_pp'][1]}% "
             f"(spread {mc['S1_rate_spread_pp']}pp)"
             + (f"; chi2(model x S1) = {mc['chi2_model_vs_S1']['chi2']:.1f}, p={mc['chi2_model_vs_S1']['p']}"
                if mc["chi2_model_vs_S1"] else "")
             + ". An evaluator that sees the model id can largely reproduce each model's baseline S1 rate.")
    L.append("- **Framing identity / template echoes.** Framings are the *treatment*, so framing-correlated "
             "surface patterns are legitimate content of the signal; the leakage risk is that a model learns the "
             "template words instead of the contrast (e.g. completions echoing the '2024 Nature study' phrasing "
             f"appear in {J['confounders']['surface_artifacts']['authority_completions_echoing_nature_study_2024_pct']:.0f}% "
             "of authority rows; 'right?' / 'i believe' echoes are common - see JSON).")
    L.append("- **Category.** Label rates differ between the two fact categories: "
             + ", ".join(f"{k}: S1 {v['S1_pct']:.1f}%, C {v['C_pct']:.1f}%, R {v['R_pct']:.1f}%"
                         for k, v in J["confounders"]["category_label_rates"].items())
             + ".")
    L.append("- **Response length.** Mean completion length by label: "
             + ", ".join(f"{k} {v['mean']:.0f}ch" for k, v in J["confounders"]["completion_len_by_label"].items()
                         if v.get("n", 0))
             + " - length is a cheap shortcut feature.")
    L.append("- **Refusal wording.** Approximate lexical check: R rows carry refusal phrases in "
             f"{J['confounders']['phrase_by_label_approximate_lexical'].get('R', {}).get('refuse_phrase_pct', 0):.0f}% "
             "of cases on completions (source check reports 92.5%); S1 rows carry agreement phrases in "
             f"{J['confounders']['phrase_by_label_approximate_lexical'].get('S1', {}).get('agree_phrase_pct', 0):.0f}% "
             "of cases.")
    L.append("- **Cross-group content.** " +
             f"{J['confounders']['surface_artifacts']['cross_group_shared_completions']} completions recur across "
             "different facts (generic one-liners shown in the group inspection).")
    L.append("")
    L.append("**Takeaway:** a per-row evaluator has several near-trivial shortcuts (model id, length, refusal "
             "wording, template echoes, category). Reported accuracy on per-row labels can then be high without "
             "the evaluator modeling actual behavioral change; any SycAudit design should hide or de-correlate "
             "these (e.g. framing-contrast supervision in units B/D, and/or withholding model id at inference).")
    L.append("")

    # ------------------------------------------------------------- 8
    L.append("## 8. Dataset size reality")
    L.append("")
    L.append(f"- Underlying structure: **{J['dataset_size_reality']['n_facts']} facts x 5 framings x "
             f"{J['dataset_size_reality']['n_models']} models**; n=50 facts, not n=7,455 independent rows.")
    L.append(f"- Pool: {J['dataset_size_reality']['pool_total_pairs']} unique (prompt, completion) pairs; "
             f"{J['dataset_size_reality']['pool_labeled_rows']} carry a label (phase-3 rows). The ~2,993 phase-4 "
             "pool rows are unlabeled until joined with their `_labeled` copies.")
    L.append("- Effective unit counts: 400 (fact x model) or 50 (fact); rows are **nested**, so row-level i.i.d. "
             "does not hold for train/val/test or for any supervised objective.")
    L.append(f"- Split implication (decision from the group inspection, not re-made here): split at the fact "
             f"level, e.g. {J['dataset_size_reality']['example_splits_at_fact_level']['train']}/"
             f"{J['dataset_size_reality']['example_splits_at_fact_level']['val']}/"
             f"{J['dataset_size_reality']['example_splits_at_fact_level']['test']} facts; per-split row counts "
             "then follow fact sizes.")
    L.append("- Generalization limits: 50 facts cover only the two question templates (30 s1_ablation_subset + 20 "
             "false-premise-health facts), one 2024-Nature-study framing convention, and 8 open-weight models; "
             "do not extrapolate quantitative S1 rates to other sycophancy setups. Source cluster-bootstrap CIs "
             "are the honest interval estimates.")
    L.append("")

    # ------------------------------------------------------------- recommendation
    L.append("## Recommended next decision")
    L.append("")
    L.append("Should the evaluator primarily **classify individual response types** or **recognize behavioral "
             "differences across controlled framing variants**? Evidence assembled in this report:")
    L.append("")
    L.append(f"1. The S1/C/H/R taxonomy is valid, consistent and fully labeled for the phase-3 pool "
             f"({J['_meta']['pool_labeled_rows']} rows), so per-row classification is *possible* - but section 7 "
             "shows a per-row model can reach high apparent accuracy via model-id / length / refusal-wording / "
             "template-echo shortcuts rather than via understanding sycophancy.")
    L.append("2. The framing effect is real yet **directionally heterogeneous**: "
             f"{largest_pos} shifts S1 by {d_pos:+.1f}pp under authority vs neutral, while "
             f"{largest_neg} shifts S1 by {d_neg:+.1f}pp; exactly {fs['facts_delta_S1_ntoa_up_gt0p5pp']} of 50 "
             "facts move one way and "
             f"{fs['facts_delta_S1_ntoa_down_lt0p5pp']} the other (pool). A single-direction 'sycophancy class' "
             "target does not fit this structure; the *direction and size of per-model and per-fact change* do.")
    L.append(f"3. At T=0 (deterministic) the change across framings is identified within (fact, model) units: "
             f"{J['t0_analysis']['signature_units_identical_label_all5']} of "
             f"{J['t0_analysis']['signature_units_with_all5_framings']} units keep one label across all 5 "
             "framings, meaning most units *do* change label under framing, and the McNemar/Wilcoxon rows in "
             "section 4 quantify which framings move S1.")
    L.append(f"4. Sampling noise at T>0 is bounded: only {stoch['cells_with_both_S1_and_nonS1_draws_pct']:.1f}% "
             "of (fact, framing, model) cells flip between S1 and non-S1 across 10 draws, i.e. most framing "
             "differences above are several times larger than within-cell sampling variation.")
    L.append("")
    L.append("**Decision.** The evaluator should primarily **recognize behavioral differences across controlled "
             "framing variants** (representation B: model x fact unit, or D: pairwise neutral-vs-framed), keeping "
             "S1/C/H/R as an **auxiliary** label head and evaluation metric rather than the sole supervised "
             "target. Rationale: the labels alone do not distinguish 'agreeing model' from 'model that changed "
             "under framing', the framing signal is the strongest stable structure in the data, and per-row "
             "classification is the branch most exposed to the section-7 confounders. This is the next decision "
             "point; unit selection, fact-level split procedure and supervision design are follow-up tasks "
             "(outside this inspection-only stage).")
    L.append("")

    OUT_MD.write_text("\n".join(L), encoding="utf-8")
    OUT_JSON.write_text(json.dumps(J, indent=2, ensure_ascii=False, default=str), encoding="utf-8")
    print(f"Wrote: {OUT_MD}")
    print(f"Wrote: {OUT_JSON}")


if __name__ == "__main__":
    main()